---
- name: Archive files
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: archive files
      archive:
        path: ["/root/file1.txt", "/usr/local/share/file2.txt", "/var/log/lastlog"]
        dest: /root/files.tar.bz2
        format: bz2
