---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Changes
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        replace: 'Listen 8080'

    - name: service restart
      service:
        name: httpd
        state: restarted
        enabled: yes