---
  - hosts: stapp01
    gather_facts: false
    become: true
    tasks:
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: tony
          group: tony
          mode: '0655'
  - hosts: stapp02
    gather_facts: false
    become: true
    tasks:
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: steve
          group: steve
          mode: '0655'
  - hosts: stapp01
    gather_facts: false
    become: true
    tasks:
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: banner
          group: banner
          mode: '0655'