---
  - hosts: all
    gather_facts: true
    become: true
    tasks:
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/data/blog.txt
          dest: /opt/data/blog.txt
          owner: tony
          group: tony
          mode: '0644'
        when: ansible_nodename == 'stapp01'
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/data/story.txt
          dest: /opt/data/story.txt
          owner: steve
          group: steve
          mode: '0644'
        when: ansible_nodename == 'stapp02'
      - name: Copying items with help of copy module
        copy:
          src: /usr/src/data/media.txt
          dest: /opt/data/media.txt
          owner: banner
          group: banner
          mode: '0644'
        when: ansible_nodename == 'stapp03'