---
  - hosts: all
    gather_facts: true
    become: true
    tasks:
      - name: Copying items with help of copy module
        when: ansible_nodename == "os-name" in groups['all']
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: tony
          group: tony
          mode: '0655'

      - name: Copying items with help of copy module
        when: ansible_nodename == "os-name" in groups['all']
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: steve
          group: steve
          mode: '0655'
      - name: Copying items with help of copy module
        when: ansible_nodename == "os-name" in groups['all']
        copy:
          src: /usr/src/finance/blog.txt
          dest: /opt/finance/blog.txt
          owner: banner
          group: banner
          mode: '0655'