---
- name: Starting
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Gather facts
      blockinfile:
        path: /root/facts.txt
        create: yes
        block: |
          Ansible managed node IP is {{ ansible_default_ipv4.address }}

    - name: httpd installation
      yum:
        name: httpd
        state: present
        
    - name: Service of httpd
      service:
        name: httpd
        enabled: true
        state: started
  
    - name: Copy file
      copy:
        src: /root/facts.txt
        dest: /var/www/html/index.html
        remote_src: yes

    - name: Rerun service
      service:
        name: httpd
        state: reloaded
